name: backup-admin
run-name: Make backup of HYC results admin DB
on:
  workflow_dispatch:
  schedule:
      - cron: 12 6 * * *
permissions:
  contents: write
  pull-requests: write
jobs:
  create-admin-backup-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: scripts/admin/requirements.txt
      - name: Update admin DB backup
        env:
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        run: |
          pip install -r scripts/admin/requirements.txt
          rm -f sources/reshyc/admin/202{5,6}_*.csv
          make admin-backup
      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Admin DB backup
          title: Admin DB backup
          add-paths: sources/reshyc/admin/
          branch: create-pull-request/admin-backup
      - name: Merge pull request
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: gh pr merge --rebase "${{ steps.cpr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Delete pull request branch
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: git push origin :create-pull-request/admin-backup
        env:
          GH_TOKEN: ${{ github.token }}
